### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [VitaeTeam/Vitae#10]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question:

      Vitae/COPYING

**Comment by Small-dev-1** [comment]
fixed in #13

**Comment by buddilla** [comment]
Not fixed enough I will fix it more... Thank god PIVX didn't notice the accidental search and replace on ohmcoin which has since been fixed. It's been that way without proper credit since dec 2017.

**Comment by Iconoclasta** [comment]
There still are issues: 


      Vitae/src/chainparams.cpp
    
and others in file sources.

**Comment by squidicuzz** [comment]
Apologies, We will get all the license headers corrected and updated.

**Comment by squidicuzz** [comment]
There is more to do, but so far I touched the majority of the main files, b5651591b1727a1d1f721c55ee1808b2770f890a

**Comment by Iconoclasta** [comment]
Thank you, we will go through your repository and double check everything has been fixed.

**Comment by buddilla** [comment]
Can we assume we are in the clear on this

**Comment by Iconoclasta** [comment]
Everything seems in order. Thanks for the collaboration. I'm closing this issue.
